// Auto-generated by generate_pins.py
// Re-run the script any time you add new photos.
// You can also hand-edit this file directly if you want to tweak a caption.
const PINS = [
  {
    "lat": 25.224992,
    "lng": -100.060639,
    "image": "images/Canavati_a_Media_Luna/IMG_7997.jpg",
    "caption": "",
    "date": "2026:08:27 07:04:35",
    "status": "reported"
  },
  {
    "lat": 25.224922,
    "lng": -100.060731,
    "image": "images/Canavati_a_Media_Luna/IMG_7999.jpg",
    "caption": "",
    "date": "2026:08:27 07:05:21",
    "status": "reported"
  },
  {
    "lat": 25.224644,
    "lng": -100.060997,
    "image": "images/Canavati_a_Media_Luna/IMG_8003.jpg",
    "caption": "",
    "date": "2026:08:27 07:06:44",
    "status": "reported"
  },
  {
    "lat": 25.224539,
    "lng": -100.061158,
    "image": "images/Canavati_a_Media_Luna/IMG_8006.jpg",
    "caption": "",
    "date": "2026:08:27 07:07:41",
    "status": "reported"
  },
  {
    "lat": 25.224603,
    "lng": -100.061119,
    "image": "images/Canavati_a_Media_Luna/IMG_8007.jpg",
    "caption": "",
    "date": "2026:08:27 07:08:01",
    "status": "reported"
  },
  {
    "lat": 25.224361,
    "lng": -100.061547,
    "image": "images/Canavati_a_Media_Luna/IMG_8011.jpg",
    "caption": "",
    "date": "2026:08:27 07:12:23",
    "status": "reported"
  },
  {
    "lat": 25.224139,
    "lng": -100.062111,
    "image": "images/Canavati_a_Media_Luna/IMG_8012.jpg",
    "caption": "",
    "date": "2026:08:27 07:14:18",
    "status": "reported"
  },
  {
    "lat": 25.224111,
    "lng": -100.062308,
    "image": "images/Canavati_a_Media_Luna/IMG_8013.jpg",
    "caption": "",
    "date": "2026:08:27 07:15:07",
    "status": "reported"
  },
  {
    "lat": 25.224056,
    "lng": -100.062819,
    "image": "images/Canavati_a_Media_Luna/IMG_8015.jpg",
    "caption": "",
    "date": "2026:08:27 07:17:07",
    "status": "reported"
  },
  {
    "lat": 25.22415,
    "lng": -100.064172,
    "image": "images/Canavati_a_Media_Luna/IMG_8023.jpg",
    "caption": "",
    "date": "2026:08:27 07:23:15",
    "status": "reported"
  },
  {
    "lat": 25.224075,
    "lng": -100.064644,
    "image": "images/Canavati_a_Media_Luna/IMG_8027.jpg",
    "caption": "",
    "date": "2026:08:27 07:25:32",
    "status": "reported"
  },
  {
    "lat": 25.22405,
    "lng": -100.064986,
    "image": "images/Canavati_a_Media_Luna/IMG_8041.jpg",
    "caption": "",
    "date": "2026:08:27 07:30:07",
    "status": "reported"
  },
  {
    "lat": 25.226178,
    "lng": -100.069183,
    "image": "images/Canavati_a_Media_Luna/IMG_8065.jpg",
    "caption": "",
    "date": "2026:08:27 07:59:49",
    "status": "reported"
  },
  {
    "lat": 25.224353,
    "lng": -100.063156,
    "image": "images/Canavati_a_Media_Luna/IMG_8080.jpg",
    "caption": "",
    "date": "2026:08:27 09:10:52",
    "status": "reported"
  },
  {
    "lat": 25.225094,
    "lng": -100.060769,
    "image": "images/Canavati_a_Media_Luna/IMG_8084.jpg",
    "caption": "",
    "date": "2026:08:27 09:16:06",
    "status": "reported"
  },
  {
    "lat": 25.225683,
    "lng": -100.060189,
    "image": "images/Canavati_a_Media_Luna/IMG_8086.jpg",
    "caption": "",
    "date": "2026:08:27 09:18:32",
    "status": "reported"
  }
];
